# Generated by Django 5.1.4 on 2025-02-24 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent', '0001_initial'),
        ('UserApp', '0002_alter_usermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='HouseType',
        ),
        migrations.AddField(
            model_name='house',
            name='house_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rent.housetype'),
        ),
        migrations.RemoveField(
            model_name='house',
            name='location',
        ),
        migrations.CreateModel(
            name='RentHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('rent_date', models.DateField(auto_now_add=True)),
                ('cancel', models.BooleanField(default=False)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rent.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Rent.location'),
        ),
    ]
